server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_livraria
spring.datasource.username=usuario_livraria
spring.datasource.password=senha_livraria
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true